---
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_version|lower|replace('/', '_') }}.yml"
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_release }}.yml"
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version|lower|replace('/', '_') }}.yml"
    - "{{ ansible_distribution|lower }}.yml"
    - "{{ ansible_os_family|lower }}.yml"
    - main.yml

- import_tasks: additional.yml
  tags:
    - development
    - docker
    - additional

- import_tasks: install.yml
  tags:
    - development
    - docker
    - install

- import_tasks: config.yml
  tags:
    - development
    - docker
    - config

- import_tasks: service.yml
  tags:
    - development
    - docker
    - service

#- include: swarm.yml
#  tags:
#    - development
#    - docker
#    - swarm

#- include: manage.yml
#  tags:
#    - development
#    - docker
#    - manage
